import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CardProvider } from "@/context/CartContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const bebasneue = Bebas_Neue({
//   subsets: ["latin"],
//   weight: ["400", "600", "700"], // you choose weights
// });

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "600", "700"], // you choose weights
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CardProvider>

          <Navbar />

          <div className="min-h-screen">
            {children}
          </div>

          <Footer />

        </CardProvider>
      </body>
    </html>
  );
}
